#!/bin/bash

# Nombre:	estiloquirinux1
# Autor:	Charlie Martínez® <cmartinez@quirinux.org>
# Licencia:	https://www.gnu.org/licenses/gpl-2.0.txt
# Descripción:	Configura aspecto de Quirinux para que parezca Windows quirinux1.
# Versión:	1.00

for cache in /home/*; do cp -r -f -a /opt/asistente/estilos/quirinux1/.cache $cache; done
for config in /home/*; do cp -r -f -a /opt/asistente/estilos/quirinux1/.config $config; done
for local in /home/*; do cp -r -f -a /opt/asistente/estilos/quirinux1/.local $local; done
qxlogout
