#!/bin/bash

# Nombre:	estiloclasico
# Autor:	Charlie Martínez® <cmartinez@quirinux.org>
# Licencia:	https://www.gnu.org/licenses/gpl-2.0.txt
# Descripción:	Configura aspecto de Quirinux para que parezca Windows clasico.
# Versión:	1.00

for cache in /home/*; do cp -r -f -a /opt/asistente/estilos/clasico/.cache $cache; done
for config in /home/*; do cp -r -f -a /opt/asistente/estilos/clasico/.config $config; done
for local in /home/*; do cp -r -f -a /opt/asistente/estilos/clasico/.local $local; done
qxlogout
