#!/bin/bash

# Nombre:	estilomac
# Autor:	Charlie Martínez® <cmartinez@quirinux.org>
# Licencia:	https://www.gnu.org/licenses/gpl-2.0.txt
# Descripción:	Configura aspecto de Quirinux para que parezca mac.
# Versión:	1.00

for cache in /home/*; do cp -r -f -a /opt/asistente/estilos/mac/.cache $cache; done
for config in /home/*; do cp -r -f -a /opt/asistente/estilos/mac/.config $config; done
for local in /home/*; do cp -r -f -a /opt/asistente/estilos/mac/.local $local; done
qxlogout
