#!/bin/bash

# Nombre:	estilomacvintage
# Autor:	Charlie Martínez® <cmartinez@quirinux.org>
# Licencia:	https://www.gnu.org/licenses/gpl-2.0.txt
# Descripción:	Configura aspecto de Quirinux para que parezca macvintage.
# Versión:	1.00

for cache in /home/*; do cp -r -f -a /opt/asistente/estilos/macvintage/.cache $cache; done
for config in /home/*; do cp -r -f -a /opt/asistente/estilos/macvintage/.config $config; done
for local in /home/*; do cp -r -f -a /opt/asistente/estilos/macvintage/.local $local; done
qxlogout
